// <auto-generated />
using BlazorEccomerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEccomerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230816193117_ProductSeeding")]
    partial class ProductSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorEccomerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "The console features a hardware on-the-fly zlib decompression module. The original PS4 model supports up to 1080p and 1080i video standards, while the Pro model supports 4K resolution.",
                            ImageUrl = "https://m.media-amazon.com/images/I/51o960aJ--L._AC_SL1000_.jpg",
                            Price = 201.99m,
                            Title = "Sony CUH-2216A PlayStation 4 Slim 500GB Games Console Jet Black"
                        },
                        new
                        {
                            Id = 2,
                            Description = "The PS5 console unleashes new gaming possibilities that you never anticipated Experience lightning-fast loading with an ultra-high-speed SSD, deeper immersion with support for haptic feedback, adaptive triggers and 3D Audio, and an all-new generation of incredible PlayStation games",
                            ImageUrl = "https://m.media-amazon.com/images/I/71p6rZnGPoL._AC_SL1500_.jpg",
                            Price = 389.00m,
                            Title = "PlayStation 5 Digital Console"
                        },
                        new
                        {
                            Id = 3,
                            Description = "7' diagonal, Optically bonded IPS LCD for enhanced readability, 1280 x 800px (16:10 aspect ratio), 60Hz, 400 nits typical 64 GB eMMC (PCIe Gen 2 x1), 16 GB LPDDR5 on-board RAM (5500 MT/s quad 32-bit channels), microSD Expansion: UHS-I supports SD, SDXC and SDHC",
                            ImageUrl = "https://m.media-amazon.com/images/I/61ekQQCkRRL._AC_SL1500_.jpg",
                            Price = 421.00m,
                            Title = "Valve Steam Deck 64GB eMMC + 16GB RAM, 7' inch, 60Hz, 1280 x 800px, SteamOS 3.0, Handheld Gaming Console"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
