// <auto-generated />
using System;
using BlazorEccomerce.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEccomerce.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230817233259_NewChanges2")]
    partial class NewChanges2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorEccomerce.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Console",
                            Url = "console"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Video Game",
                            Url = "videogame"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Accessories",
                            Url = "accessories"
                        });
                });

            modelBuilder.Entity("BlazorEccomerce.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Developer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A new generation of gaming with enhanced graphics and social features.\r\nThe Dualshock controller has been redesigned and enhanced for a more comfortable and responsive gameplay experience.",
                            Developer = "Sony",
                            ImageUrl = "https://www-konga-com-res.cloudinary.com/w_400,f_auto,fl_lossy,dpr_3.0,q_auto/media/catalog/product/L/Y/124977_1646511717.jpg",
                            Price = 119.99m,
                            ReleaseYear = 2016,
                            Title = "PlayStation 4 500GB - Good Condition"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "PlayStation 4 Pro - the super charged PS4 - take play to the next level with PS4 Pro: See every detail explode into life with 4K gaming and entertainment, experience faster, smoother frame rates and more powerful gaming performance and enjoy richer, more vibrant colours with HDR technology.",
                            Developer = "Sony",
                            ImageUrl = "https://m.media-amazon.com/images/I/61UZ8FqIUWL._AC_SL1500_.jpg",
                            Price = 269.99m,
                            ReleaseYear = 2016,
                            Title = "Sony PlayStation 4 Pro Console - Black - 1TB (Renewed)"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "The console features a hardware on-the-fly zlib decompression module. The original PS4 model supports up to 1080p and 1080i video standards, while the Pro model supports 4K resolution.",
                            Developer = "Sony",
                            ImageUrl = "https://m.media-amazon.com/images/I/51o960aJ--L._AC_SL1000_.jpg",
                            Price = 201.99m,
                            ReleaseYear = 2016,
                            Title = "Sony CUH-2216A PlayStation 4 Slim 500GB Games Console Jet Black"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "The PS5 console unleashes new gaming possibilities that you never anticipated Experience lightning-fast loading with an ultra-high-speed SSD, deeper immersion with support for haptic feedback, adaptive triggers and 3D Audio, and an all-new generation of incredible PlayStation games",
                            Developer = "Sony",
                            ImageUrl = "https://m.media-amazon.com/images/I/71p6rZnGPoL._AC_SL1500_.jpg",
                            Price = 389.00m,
                            ReleaseYear = 2020,
                            Title = "PlayStation 5 Digital Console"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "7' diagonal, Optically bonded IPS LCD for enhanced readability, 1280 x 800px (16:10 aspect ratio), 60Hz, 400 nits typical 64 GB eMMC (PCIe Gen 2 x1), 16 GB LPDDR5 on-board RAM (5500 MT/s quad 32-bit channels), microSD Expansion: UHS-I supports SD, SDXC and SDHC",
                            Developer = "Steam",
                            ImageUrl = "https://m.media-amazon.com/images/I/61ekQQCkRRL._AC_SL1500_.jpg",
                            Price = 421.00m,
                            ReleaseYear = 2022,
                            Title = "Valve Steam Deck 64GB eMMC + 16GB RAM, 7' inch, 60Hz, 1280 x 800px, SteamOS 3.0, Handheld Gaming Console"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "PC gaming has never been this portable - the ASUS ROG Ally puts a Windows gaming machine in the palm of your hands. And it doesn't compromise on specs. It packs an impressive AMD Ryzen Z1 Extreme CPU with Radeon graphics. So it's got plenty of horsepower to run your favourites. They'll look amazing on the 7” Full HD touchscreen. And with refresh rate up to 120 Hz, they'll be gloriously smooth, too. To match the amazing visuals, there are Dolby Atmos speakers that'll draw you into the game. And with battery life up to 8 hours, you can have a proper gaming sesh wherever you are.",
                            Developer = "ASUS",
                            ImageUrl = "https://media.currys.biz/i/currysprod/10249544?$l-large$&fmt=auto",
                            Price = 699.00m,
                            ReleaseYear = 2023,
                            Title = "ASUS ROG Ally Handheld Gaming Console"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Introducing the Xbox Series S, the smallest, sleekest Xbox console ever. Experience the speed and performance of a next-gen all-digital console at an accessible price point. Go all-digital and enjoy disc-free, next-gen gaming with the smallest Xbox console ever made.",
                            Developer = "Microsoft",
                            ImageUrl = "https://m.media-amazon.com/images/I/61mnlvScHxL._AC_SL1500_.jpg",
                            Price = 249.99m,
                            ReleaseYear = 2020,
                            Title = "Xbox Series S"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Introducing Xbox Series X, the fastest, most powerful Xbox ever. Play thousands of titles from four generations of consoles—all games look and play best on Xbox Series X.",
                            Developer = "Microsoft",
                            ImageUrl = "https://m.media-amazon.com/images/I/41NhM7MMj4L._AC_SL1080_.jpg",
                            Price = 469.23m,
                            ReleaseYear = 2020,
                            Title = "Xbox Series X"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 1,
                            Description = "Rediscover your favourite 80s videogames in HD! Each title for the Nintendo Classic Mini: Nintendo Entertainment System is displayed at a smooth 60Hz via the included HDMI cable and can be enjoyed in one of three visual modes!.",
                            Developer = "Nintendo",
                            ImageUrl = "https://m.media-amazon.com/images/I/71GIan4mDmL._AC_SL1500_.jpg",
                            Price = 199.96m,
                            ReleaseYear = 1985,
                            Title = "Nintendo Classic Mini: Nintendo Entertainment System (Electronic Games)"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Description = "The Nintendo Classic Mini: Super Nintendo Entertainment System has the same look and feel of the original system only smaller and comes pre-loaded with 21 games.Launched in Europe in 1992, the Super Nintendo introduced what many consider some of the greatest video games of all timeX.",
                            Developer = "Nintendo",
                            ImageUrl = "https://m.media-amazon.com/images/I/81SVwPdq3tL._AC_SL1500_.jpg",
                            Price = 268.39m,
                            ReleaseYear = 1992,
                            Title = "Nintendo Classic Mini Console: Super Nintendo Entertainment System"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "The new system features a vibrant 7-inch OLED screen, a wide adjustable stand, a dock with a wired LAN port, 64 GB of internal storage, and enhanced audio.",
                            Developer = "Nintendo",
                            ImageUrl = "https://m.media-amazon.com/images/I/51K6gw94TRL._AC_SL1200_.jpg",
                            Price = 289.00m,
                            ReleaseYear = 2021,
                            Title = "Nintendo Switch (OLED Model) - White"
                        });
                });

            modelBuilder.Entity("BlazorEccomerce.Shared.Product", b =>
                {
                    b.HasOne("BlazorEccomerce.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
